services:
  # Frontend Service
  - type: web
    name: telesync-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://telesync-backend-jkqs.onrender.com/api
      - key: VITE_WS_URL
        value: wss://telesync-backend-jkqs.onrender.com
      - key: VITE_SUPABASE_URL
        value: https://iausgqikbmhkkicmuzei.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhdXNncWlrYm1oa2tpY211emVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTQ2NjEsImV4cCI6MjA3MzM3MDY2MX0.EGXA8llbbTQ3QvhttQN_sIklVM0ymBQ0VZ2qYva45js

  # Backend Service
  - type: web
    name: telesync-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: WEB_APP_URL
        value: https://telesync-backend-jkqs.onrender.com
      - key: SUPABASE_URL
        value: https://iausgqikbmhkkicmuzei.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhdXNncWlrYm1oa2tpY211emVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTQ2NjEsImV4cCI6MjA3MzM3MDY2MX0.EGXA8llbbTQ3QvhttQN_sIklVM0ymBQ0VZ2qYva45js